.TH "code/src Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBclient\fP"
.br
.ti -1c
.RI "directory \fBclient\-game\fP"
.br
.ti -1c
.RI "directory \fBdisplay_game\fP"
.br
.ti -1c
.RI "directory \fBeditor\fP"
.br
.ti -1c
.RI "directory \fBgame\-control\fP"
.br
.ti -1c
.RI "directory \fBglobal\fP"
.br
.ti -1c
.RI "directory \fBncurses\fP"
.br
.ti -1c
.RI "directory \fBserver\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient\-game\&.c\fP"
.br
.ti -1c
.RI "file \fBclient\&.c\fP"
.br
.RI "File that manages the client\&. "
.ti -1c
.RI "file \fBeditor\&.c\fP"
.br
.ti -1c
.RI "file \fBgame\-control\-test\&.c\fP"
.br
.ti -1c
.RI "file \fBserver\&.c\fP"
.br
.RI "File that manages the server\&. "
.in -1c
