.TH "code/include/global Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/global Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaddress_table\&.h\fP"
.br
.RI "File that manage address_table\&. "
.ti -1c
.RI "file \fBfunction\&.h\fP"
.br
.RI "Files that contains the functions used in the project\&. "
.ti -1c
.RI "file \fBgame\&.h\fP"
.br
.RI "File that manages the data structures of the games\&. "
.ti -1c
.RI "file \fBnetwork_request\&.h\fP"
.br
.RI "File that manages the requests and responses of the network between the client and the server\&. "
.ti -1c
.RI "file \fBsprite\&.h\fP"
.br
.RI "File that manage sprite\&. "
.in -1c
