.TH "code/include/server Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/server Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcreate_game\&.h\fP"
.br
.RI "File that manages the creation of a game for the server\&. "
.ti -1c
.RI "file \fBinfo_client\&.h\fP"
.br
.RI "File that manages the information of the clients with data structures\&. "
.ti -1c
.RI "file \fBserver_tcp\&.h\fP"
.br
.RI "File that manages the TCP server\&. "
.ti -1c
.RI "file \fBserver_udp\&.h\fP"
.br
.RI "File that manages the UDP server\&. "
.in -1c
