.TH "code/include/editor Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/editor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBelement_game_level\&.h\fP"
.br
.RI "Files that manage element of a game_level\&. "
.ti -1c
.RI "file \fBfile_game_level\&.h\fP"
.br
.RI "File that manage a file of game_level (file \&.world) "
.ti -1c
.RI "file \fBgame_level\&.h\fP"
.br
.RI "File that manage a game_level\&. "
.ti -1c
.RI "file \fBinterface\&.h\fP"
.br
.RI "File that manage a interface of editor\&. "
.ti -1c
.RI "file \fBpaint_tools\&.h\fP"
.br
.RI "File that manage a paint_tool\&. "
.in -1c
