.TH "code/src/editor Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src/editor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBelement_game_level\&.c\fP"
.br
.ti -1c
.RI "file \fBfile_game_level\&.c\fP"
.br
.ti -1c
.RI "file \fBgame_level\&.c\fP"
.br
.ti -1c
.RI "file \fBinterface\&.c\fP"
.br
.ti -1c
.RI "file \fBpaint_tools\&.c\fP"
.br
.in -1c
