.TH "code/include/display_game Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/display_game Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterface_game\&.h\fP"
.br
.RI "This file manages the ncurses interface for the game display\&. "
.ti -1c
.RI "file \fBlevel_display\&.h\fP"
.br
.RI "This file allows to define the methods and structures to display the state of a level\&. "
.in -1c
