.TH "code/include/ncurses Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/ncurses Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolors\&.h\fP"
.br
.ti -1c
.RI "file \fBfunctions\&.h\fP"
.br
.ti -1c
.RI "file \fBwindow\&.h\fP"
.br
.in -1c
