.TH "code/src/game-control Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src/game-control Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBenemy\&.c\fP"
.br
.ti -1c
.RI "file \fBentity\&.c\fP"
.br
.ti -1c
.RI "file \fBgame_control\&.c\fP"
.br
.ti -1c
.RI "file \fBlevel_info\&.c\fP"
.br
.ti -1c
.RI "file \fBmove_world\&.c\fP"
.br
.ti -1c
.RI "file \fBplayer\&.c\fP"
.br
.ti -1c
.RI "file \fBtrap\&.c\fP"
.br
.ti -1c
.RI "file \fBworld_info\&.c\fP"
.br
.in -1c
