.TH "code/include/client Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/client Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient_create_game\&.h\fP"
.br
.RI "\&.h file of the client allowing the creation of a game "
.ti -1c
.RI "file \fBclient_join_game\&.h\fP"
.br
.RI "File that manages when a customer joins an already created game\&. "
.ti -1c
.RI "file \fBclient_tcp\&.h\fP"
.br
.RI "File that manages the TCP client\&. "
.ti -1c
.RI "file \fBclient_udp\&.h\fP"
.br
.RI "File that manages the UDP client\&. "
.ti -1c
.RI "file \fBclient_utility\&.h\fP"
.br
.RI "Various useful functions for the customer\&. "
.in -1c
