.TH "code/include/client-game Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/client-game Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient\-game\&.h\fP"
.br
.RI "File that manages the client in a game\&. "
.ti -1c
.RI "file \fBrequest_exchange\&.h\fP"
.br
.RI "File that descrive different request of exchange between a game client and game server\&. "
.in -1c
