.TH "code/src/global Directory Reference" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src/global Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaddress_table\&.c\fP"
.br
.ti -1c
.RI "file \fBfunction\&.c\fP"
.br
.ti -1c
.RI "file \fBgame\&.c\fP"
.br
.RI "File that manages the data structures of the games\&. "
.ti -1c
.RI "file \fBnetwork_request\&.c\fP"
.br
.RI "File that manages the network requests\&. "
.ti -1c
.RI "file \fBsprite\&.c\fP"
.br
.in -1c
