.TH "client_game_infos_thread_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_game_infos_thread_t \- Structure that contains informations transmit at thread_display\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client\-game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfreeze\fP"
.br
.ti -1c
.RI "int \fBend_game\fP"
.br
.ti -1c
.RI "int * \fBsocket_client\fP"
.br
.ti -1c
.RI "\fBinterface_game_t\fP * \fBinterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains informations transmit at thread_display\&. 


.PP
Definition at line 23 of file client\-game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int end_game"

.PP
Definition at line 26 of file client\-game\&.h\&.
.SS "int freeze"

.PP
Definition at line 25 of file client\-game\&.h\&.
.SS "\fBinterface_game_t\fP* interface"

.PP
Definition at line 28 of file client\-game\&.h\&.
.SS "int* socket_client"

.PP
Definition at line 27 of file client\-game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
