.TH "code/src/client/client_tcp.c" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src/client/client_tcp.c \- Files that manages the TCP client\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'client_tcp\&.h'\fP
.br
\fC#include 'functions\&.h'\fP
.br
\fC#include 'client\-game\&.h'\fP
.br
\fC#include 'interface_game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconnect_to_server_with_tcp\fP (int \fBport\fP, char \fBaddress_ip\fP[15])"
.br
.RI "Connect to the server with TCP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Files that manages the TCP client\&. 


.PP
\fBAuthor\fP
.RS 4
HADID Hocine & CHEMIN Pierre 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-03-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBclient_tcp\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void connect_to_server_with_tcp (int port, char address_ip[15])"

.PP
Connect to the server with TCP\&. 
.PP
\fBParameters\fP
.RS 4
\fIport\fP 
.br
\fIaddress_ip\fP 
.RE
.PP

.PP
Definition at line 35 of file client_tcp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
