.TH "code/include/ncurses/colors.h" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/ncurses/colors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWHITE\fP   1"
.br
.ti -1c
.RI "#define \fBGREEN\fP   2"
.br
.ti -1c
.RI "#define \fBBLUE\fP   3"
.br
.ti -1c
.RI "#define \fBRED\fP   4"
.br
.ti -1c
.RI "#define \fBYELLOW\fP   5"
.br
.ti -1c
.RI "#define \fBCYAN\fP   6"
.br
.ti -1c
.RI "#define \fBMAGENTA\fP   7"
.br
.ti -1c
.RI "#define \fBFD_WHITE\fP   8"
.br
.ti -1c
.RI "#define \fBFD_GREEN\fP   9"
.br
.ti -1c
.RI "#define \fBFD_BLUE\fP   10"
.br
.ti -1c
.RI "#define \fBFD_RED\fP   11"
.br
.ti -1c
.RI "#define \fBFD_YELLOW\fP   12"
.br
.ti -1c
.RI "#define \fBFD_CYAN\fP   13"
.br
.ti -1c
.RI "#define \fBFD_MAGENTA\fP   14"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpalette\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLUE   3"

.PP
Definition at line 7 of file colors\&.h\&.
.SS "#define CYAN   6"

.PP
Definition at line 10 of file colors\&.h\&.
.SS "#define FD_BLUE   10"

.PP
Definition at line 14 of file colors\&.h\&.
.SS "#define FD_CYAN   13"

.PP
Definition at line 17 of file colors\&.h\&.
.SS "#define FD_GREEN   9"

.PP
Definition at line 13 of file colors\&.h\&.
.SS "#define FD_MAGENTA   14"

.PP
Definition at line 18 of file colors\&.h\&.
.SS "#define FD_RED   11"

.PP
Definition at line 15 of file colors\&.h\&.
.SS "#define FD_WHITE   8"

.PP
Definition at line 12 of file colors\&.h\&.
.SS "#define FD_YELLOW   12"

.PP
Definition at line 16 of file colors\&.h\&.
.SS "#define GREEN   2"

.PP
Definition at line 6 of file colors\&.h\&.
.SS "#define MAGENTA   7"

.PP
Definition at line 11 of file colors\&.h\&.
.SS "#define RED   4"

.PP
Definition at line 8 of file colors\&.h\&.
.SS "#define WHITE   1"

.PP
Definition at line 5 of file colors\&.h\&.
.SS "#define YELLOW   5"

.PP
Definition at line 9 of file colors\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void palette ()"
Palette definition\&. 
.PP
Definition at line 8 of file colors\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
