.TH "content_response_server_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content_response_server_t \- Structure that contains the content of the response of the server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network_request\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnb_clients\fP"
.br
.ti -1c
.RI "int \fBid_clients\fP"
.br
.ti -1c
.RI "int \fBport_tcp\fP"
.br
.ti -1c
.RI "\fBlist_world_response_t\fP \fBlist_world\fP"
.br
.ti -1c
.RI "\fBlist_game_without_pointers_t\fP \fBlist_game\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the content of the response of the server\&. 


.PP
Definition at line 64 of file network_request\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int id_clients"

.PP
Definition at line 67 of file network_request\&.h\&.
.SS "\fBlist_game_without_pointers_t\fP list_game"

.PP
Definition at line 70 of file network_request\&.h\&.
.SS "\fBlist_world_response_t\fP list_world"

.PP
Definition at line 69 of file network_request\&.h\&.
.SS "int nb_clients"

.PP
Definition at line 66 of file network_request\&.h\&.
.SS "int port_tcp"

.PP
Definition at line 68 of file network_request\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
