.TH "content_request_client_udp_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content_request_client_udp_t \- Structure that contains the content of the request of the client\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network_request\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpseudo\fP [\fBMAX_MSG\fP]"
.br
.ti -1c
.RI "int \fBid_client\fP"
.br
.ti -1c
.RI "int \fBsettings_game\fP [3]"
.br
.ti -1c
.RI "int \fBchoice_game\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the content of the request of the client\&. 


.PP
Definition at line 42 of file network_request\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int choice_game[2]"

.PP
Definition at line 47 of file network_request\&.h\&.
.SS "int id_client"

.PP
Definition at line 45 of file network_request\&.h\&.
.SS "char pseudo[\fBMAX_MSG\fP]"

.PP
Definition at line 44 of file network_request\&.h\&.
.SS "int settings_game[3]"

.PP
Definition at line 46 of file network_request\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
