.TH "element_game_level_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
element_game_level_t \- An element of game_level\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <element_game_level\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBposX\fP"
.br
.ti -1c
.RI "int \fBposY\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "\fBsprite_t\fP \fBsprite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An element of game_level\&. 


.PP
Definition at line 20 of file element_game_level\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int height"

.PP
Definition at line 25 of file element_game_level\&.h\&.
.SS "int posX"

.PP
Definition at line 22 of file element_game_level\&.h\&.
.SS "int posY"

.PP
Definition at line 23 of file element_game_level\&.h\&.
.SS "\fBsprite_t\fP sprite"

.PP
Definition at line 26 of file element_game_level\&.h\&.
.SS "int width"

.PP
Definition at line 24 of file element_game_level\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
