.TH "enemy_infos_thread_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemy_infos_thread_t \- The information transmitted to an enemy's thread\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game_control\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "int \fBid_enemy\fP"
.br
.ti -1c
.RI "\fBgame_control_t\fP * \fBgame_control\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The information transmitted to an enemy's thread\&. 


.PP
Definition at line 41 of file game_control\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBgame_control_t\fP* game_control"

.PP
Definition at line 44 of file game_control\&.h\&.
.SS "int id_enemy"

.PP
Definition at line 43 of file game_control\&.h\&.
.SS "int level"

.PP
Definition at line 42 of file game_control\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
