.TH "code/src/game-control/enemy.c" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src/game-control/enemy.c
.SH SYNOPSIS
.br
.PP
\fC#include 'enemy\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'game_control\&.h'\fP
.br
\fC#include 'move_world\&.h'\fP
.br
\fC#include 'entity\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialise_enemy\fP (\fBenemy_t\fP *enemy, \fBtype_enemy_enum\fP type)"
.br
.RI "Initialize an enemy\&. "
.ti -1c
.RI "void * \fBthread_enemy\fP (void *arg)"
.br
.RI "thread of operation of an enemy "
.ti -1c
.RI "int \fBdirection_alea\fP (\fBtype_enemy_enum\fP type_enemy)"
.br
.RI "Gets a random direction depending on the type of an enemy\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int direction_alea (\fBtype_enemy_enum\fP type_enemy)"

.PP
Gets a random direction depending on the type of an enemy\&. 
.PP
\fBParameters\fP
.RS 4
\fItype_enemy\fP The type of the enemy 
.RE
.PP
\fBReturns\fP
.RS 4
int The random direction 
.RE
.PP

.PP
Definition at line 66 of file enemy\&.c\&.
.SS "void initialise_enemy (\fBenemy_t\fP * enemy, \fBtype_enemy_enum\fP type)"

.PP
Initialize an enemy\&. 
.PP
\fBParameters\fP
.RS 4
\fIenemy\fP Enemy initialized 
.br
\fItype\fP The type of the enemy 
.RE
.PP

.PP
Definition at line 11 of file enemy\&.c\&.
.SS "void* thread_enemy (void * arg)"

.PP
thread of operation of an enemy 
.PP
\fBParameters\fP
.RS 4
\fIarg\fP The necessary information in the form of the \fBenemy_infos_thread_t\fP structure 
.RE
.PP
\fBReturns\fP
.RS 4
void* The result of this Thread - there is NULL 
.RE
.PP

.PP
Definition at line 15 of file enemy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
