.TH "enemy_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemy_t \- Represents an enemys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enemy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtype_enemy_enum\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an enemys\&. 


.PP
Definition at line 30 of file enemy\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtype_enemy_enum\fP type"

.PP
Definition at line 32 of file enemy\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
