.TH "code/include/game-control/entity.h" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/game-control/entity.h \- File that manage an entity\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sprite\&.h'\fP
.br
\fC#include 'player\&.h'\fP
.br
\fC#include 'enemy\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBentity_t\fP"
.br
.RI "A game entity\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtype_entity_enum\fP { \fBPLAYER\fP = 1, \fBENEMY\fP = 2 }"
.br
.RI "The type of the entity\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialise_entity\fP (\fBentity_t\fP *entity, \fBtype_entity_enum\fP type, int posX, int posY)"
.br
.RI "Initialize an entity\&. "
.ti -1c
.RI "int \fBposX_width_entity\fP (\fBentity_t\fP entity)"
.br
.RI "Allows you to obtain the width of an entity\&. "
.ti -1c
.RI "int \fBposY_height_entity\fP (\fBentity_t\fP entity)"
.br
.RI "Allows you to obtain the height of an entity\&. "
.in -1c
.SH "Detailed Description"
.PP 
File that manage an entity\&. 


.PP
\fBAuthor\fP
.RS 4
HADID Hocine & CHEMIN Pierre 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-03-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBentity\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtype_entity_enum\fP"

.PP
The type of the entity\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPLAYER \fP\fP
.TP
\fB\fIENEMY \fP\fP
.PP
Definition at line 23 of file entity\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void initialise_entity (\fBentity_t\fP * entity, \fBtype_entity_enum\fP type, int posX, int posY)"

.PP
Initialize an entity\&. 
.PP
\fBParameters\fP
.RS 4
\fIentity\fP The entity that is initialized 
.br
\fItype\fP The type of the entitys 
.br
\fIposX\fP Position X of the entity 
.br
\fIposY\fP Position Y of the entity 
.RE
.PP

.PP
Definition at line 5 of file entity\&.c\&.
.SS "int posX_width_entity (\fBentity_t\fP entity)"

.PP
Allows you to obtain the width of an entity\&. 
.PP
\fBParameters\fP
.RS 4
\fIentity\fP The entity whose width we want 
.RE
.PP
\fBReturns\fP
.RS 4
int The width of the entity 
.RE
.PP

.PP
Definition at line 12 of file entity\&.c\&.
.SS "int posY_height_entity (\fBentity_t\fP entity)"

.PP
Allows you to obtain the height of an entity\&. 
.PP
\fBParameters\fP
.RS 4
\fIentity\fP The entity whose height we want 
.RE
.PP
\fBReturns\fP
.RS 4
int The height of the entity 
.RE
.PP

.PP
Definition at line 30 of file entity\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
