.TH "entry_address_table_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entry_address_table_t \- An entry in the address table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <address_table\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "off_t \fBposition\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An entry in the address table\&. 


.PP
Definition at line 23 of file address_table\&.h\&.
.SH "Field Documentation"
.PP 
.SS "off_t position"

.PP
Definition at line 25 of file address_table\&.h\&.
.SS "size_t size"

.PP
Definition at line 26 of file address_table\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
