.TH "file_game_level_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_game_level_t \- Structure of a file of game_level\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <file_game_level\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBaddress_table_t\fP \fBaddress_table\fP"
.br
.ti -1c
.RI "\fBaddress_table_t\fP \fBaddress_table_void\fP"
.br
.ti -1c
.RI "int \fBcurrent_index_address_table\fP"
.br
.ti -1c
.RI "int \fBfile_descriptor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of a file of game_level\&. 


.PP
Definition at line 23 of file file_game_level\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBaddress_table_t\fP address_table"

.PP
Definition at line 25 of file file_game_level\&.h\&.
.SS "\fBaddress_table_t\fP address_table_void"

.PP
Definition at line 26 of file file_game_level\&.h\&.
.SS "int current_index_address_table"

.PP
Definition at line 27 of file file_game_level\&.h\&.
.SS "int file_descriptor"

.PP
Definition at line 28 of file file_game_level\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
