.TH "code/src/global/function.c" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/src/global/function.c
.SH SYNOPSIS
.br
.PP
\fC#include 'function\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBget_timestamp\fP ()"
.br
.RI "Obtain the current date and time\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
your name (you@domain.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-03-29
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBfunction\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "char* get_timestamp ()"

.PP
Obtain the current date and time\&. 
.PP
\fBReturns\fP
.RS 4
char* 
.RE
.PP

.PP
Definition at line 22 of file function\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
