.TH "code/include/ncurses/functions.h" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/ncurses/functions.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBncurses_init\fP ()"
.br
.ti -1c
.RI "void \fBncurses_stop\fP ()"
.br
.ti -1c
.RI "void \fBncurses_colors\fP ()"
.br
.ti -1c
.RI "void \fBncurses_init_mouse\fP ()"
.br
.ti -1c
.RI "int \fBmouse_getpos\fP (int *x, int *y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int mouse_getpos (int * x, int * y)"
Get the mouse position\&. 
.PP
Definition at line 54 of file functions\&.c\&.
.SS "void ncurses_colors ()"
Colors initialisation\&. 
.PP
Definition at line 28 of file functions\&.c\&.
.SS "void ncurses_init ()"
ncurses initialisation\&. 
.PP
Definition at line 9 of file functions\&.c\&.
.SS "void ncurses_init_mouse ()"
Mouse initialisation\&. 
.PP
Definition at line 43 of file functions\&.c\&.
.SS "void ncurses_stop ()"
Stop ncurses\&. 
.PP
Definition at line 21 of file functions\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
