.TH "game_level_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game_level_t \- Represent a game_level\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game_level\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBelement_game_level_t\fP * \fBelements_map\fP [\fBWIDTH_LEVEL_GAME\fP][\fBHEIGHT_LEVEL_GAME\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represent a game_level\&. 


.PP
Definition at line 25 of file game_level\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBelement_game_level_t\fP* elements_map[\fBWIDTH_LEVEL_GAME\fP][\fBHEIGHT_LEVEL_GAME\fP]"

.PP
Definition at line 27 of file game_level\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
