.TH "game_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game_t \- Structure that contains the information of a game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBnb_participants_final\fP"
.br
.ti -1c
.RI "int \fBnb_participants_actual\fP"
.br
.ti -1c
.RI "char \fBname_world\fP [\fBMAX_MSG\fP]"
.br
.ti -1c
.RI "\fBlist_info_client_t\fP * \fBlist_players\fP"
.br
.ti -1c
.RI "struct \fBgame_t\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBgame_t\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the information of a game\&. 


.PP
Definition at line 23 of file game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int id"

.PP
Definition at line 25 of file game\&.h\&.
.SS "\fBlist_info_client_t\fP* list_players"

.PP
Definition at line 29 of file game\&.h\&.
.SS "char name_world[\fBMAX_MSG\fP]"

.PP
Definition at line 28 of file game\&.h\&.
.SS "int nb_participants_actual"

.PP
Definition at line 27 of file game\&.h\&.
.SS "int nb_participants_final"

.PP
Definition at line 26 of file game\&.h\&.
.SS "struct \fBgame_t\fP* next"

.PP
Definition at line 30 of file game\&.h\&.
.SS "struct \fBgame_t\fP* prev"

.PP
Definition at line 31 of file game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
