.TH "infos_bomb_explose_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
infos_bomb_explose_t \- Information for the thread of a bomb explosion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <move_world\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBposition\fP [2]"
.br
.ti -1c
.RI "int \fBnumber_players\fP"
.br
.ti -1c
.RI "int \fBnumber_enemy\fP"
.br
.ti -1c
.RI "int \fBdelay_explosion\fP"
.br
.ti -1c
.RI "int \fBid_level\fP"
.br
.ti -1c
.RI "\fBworld_info_t\fP * \fBworld_info\fP"
.br
.ti -1c
.RI "\fBentity_t\fP * \fBenemy_level\fP"
.br
.ti -1c
.RI "\fBentity_t\fP * \fBplayers\fP"
.br
.ti -1c
.RI "\fBtype_sprite_enum\fP \fBlast_sprite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information for the thread of a bomb explosion\&. 


.PP
Definition at line 46 of file move_world\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int delay_explosion"

.PP
Definition at line 51 of file move_world\&.h\&.
.SS "\fBentity_t\fP* enemy_level"

.PP
Definition at line 54 of file move_world\&.h\&.
.SS "int id_level"

.PP
Definition at line 52 of file move_world\&.h\&.
.SS "\fBtype_sprite_enum\fP last_sprite"

.PP
Definition at line 56 of file move_world\&.h\&.
.SS "int number_enemy"

.PP
Definition at line 50 of file move_world\&.h\&.
.SS "int number_players"

.PP
Definition at line 49 of file move_world\&.h\&.
.SS "\fBentity_t\fP* players"

.PP
Definition at line 55 of file move_world\&.h\&.
.SS "int position[2]"

.PP
Definition at line 48 of file move_world\&.h\&.
.SS "\fBworld_info_t\fP* world_info"

.PP
Definition at line 53 of file move_world\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
