.TH "infos_wait_item_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
infos_wait_item_t \- Information for the thread waiting for an item to reappear\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <move_world\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBinfos\fP [3]"
.br
.ti -1c
.RI "\fBlevel_info_t\fP * \fBlevel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information for the thread waiting for an item to reappear\&. 


.PP
Definition at line 36 of file move_world\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int infos[3]"

.PP
Definition at line 38 of file move_world\&.h\&.
.SS "\fBlevel_info_t\fP* level"

.PP
Definition at line 39 of file move_world\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
