.TH "infos_end_thread_properly_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
infos_end_thread_properly_t \- Structure that contains informations transmit at end_thread_player_properly\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <player\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "\fBgame_control_t\fP * \fBgame_control_infos\fP"
.br
.ti -1c
.RI "\fBplayer_t\fP * \fBplayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains informations transmit at end_thread_player_properly\&. 
.PP
Definition at line 37 of file player\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBgame_control_t\fP* game_control_infos"

.PP
Definition at line 40 of file player\&.h\&.
.SS "\fBplayer_t\fP* player"

.PP
Definition at line 41 of file player\&.h\&.
.SS "int socket"

.PP
Definition at line 39 of file player\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
