.TH "interface_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface_t \- Structure representing the interface of an editor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwindow_t\fP * \fBwin_infos\fP"
.br
.ti -1c
.RI "\fBwindow_t\fP * \fBwin_level\fP"
.br
.ti -1c
.RI "\fBwindow_t\fP * \fBwin_tools\fP"
.br
.ti -1c
.RI "\fBfile_game_level_t\fP \fBfile_game_level\fP"
.br
.ti -1c
.RI "\fBgame_level_t\fP \fBgame_level\fP"
.br
.ti -1c
.RI "\fBpaint_tool_t\fP \fBpaint_tool\fP"
.br
.ti -1c
.RI "int \fBid_door\fP"
.br
.ti -1c
.RI "int \fBid_gate\fP"
.br
.ti -1c
.RI "int \fBid_key\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing the interface of an editor\&. 


.PP
Definition at line 29 of file interface\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBfile_game_level_t\fP file_game_level"

.PP
Definition at line 35 of file interface\&.h\&.
.SS "\fBgame_level_t\fP game_level"

.PP
Definition at line 37 of file interface\&.h\&.
.SS "int id_door"

.PP
Definition at line 40 of file interface\&.h\&.
.SS "int id_gate"

.PP
Definition at line 41 of file interface\&.h\&.
.SS "int id_key"

.PP
Definition at line 42 of file interface\&.h\&.
.SS "\fBpaint_tool_t\fP paint_tool"

.PP
Definition at line 38 of file interface\&.h\&.
.SS "\fBwindow_t\fP* win_infos"

.PP
Definition at line 31 of file interface\&.h\&.
.SS "\fBwindow_t\fP* win_level"

.PP
Definition at line 32 of file interface\&.h\&.
.SS "\fBwindow_t\fP* win_tools"

.PP
Definition at line 33 of file interface\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
