.TH "interface_game_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface_game_t \- The structure of the interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface_game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwindow_t\fP * \fBwin_level\fP"
.br
.ti -1c
.RI "\fBwindow_t\fP * \fBwin_infos\fP"
.br
.ti -1c
.RI "\fBwindow_t\fP * \fBwin_message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure of the interface\&. 


.PP
Definition at line 26 of file interface_game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBwindow_t\fP* win_infos"

.PP
Definition at line 29 of file interface_game\&.h\&.
.SS "\fBwindow_t\fP* win_level"

.PP
Definition at line 28 of file interface_game\&.h\&.
.SS "\fBwindow_t\fP* win_message"

.PP
Definition at line 30 of file interface_game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
