.TH "list_block_trap_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_block_trap_t \- A list of trap blocks\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlist_trap_t\fP * \fBblocks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A list of trap blocks\&. 


.PP
Definition at line 42 of file trap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlist_trap_t\fP* blocks"

.PP
Definition at line 44 of file trap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
