.TH "list_game_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_game_t \- Structure that contains the list of games\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgame_t\fP * \fBhead\fP"
.br
.ti -1c
.RI "int \fBnb_games\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the list of games\&. 


.PP
Definition at line 39 of file game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBgame_t\fP* head"

.PP
Definition at line 41 of file game\&.h\&.
.SS "int nb_games"

.PP
Definition at line 42 of file game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
