.TH "list_world_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_world_t \- Structure that contains the list of worlds\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create_game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct dirent ** \fBname_world\fP"
.br
.ti -1c
.RI "int \fBnb_world\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the list of worlds\&. 


.PP
Definition at line 25 of file create_game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct dirent** name_world"

.PP
Definition at line 27 of file create_game\&.h\&.
.SS "int nb_world"

.PP
Definition at line 28 of file create_game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
