.TH "list_info_client_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_info_client_t \- Structure that contains the list of clients\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <info_client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBinfo_client_t\fP * \fBhead\fP"
.br
.ti -1c
.RI "int \fBnb_clients\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the list of clients\&. 


.PP
Definition at line 36 of file info_client\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBinfo_client_t\fP* head"

.PP
Definition at line 38 of file info_client\&.h\&.
.SS "int nb_clients"

.PP
Definition at line 39 of file info_client\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
