.TH "list_world_response_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_world_response_t \- Structure that contains the list of worlds without pointers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create_game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname_world\fP [255][255]"
.br
.ti -1c
.RI "int \fBnb_world\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the list of worlds without pointers\&. 


.PP
Definition at line 35 of file create_game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char name_world[255][255]"

.PP
Definition at line 37 of file create_game\&.h\&.
.SS "int nb_world"

.PP
Definition at line 38 of file create_game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
