.TH "paint_tool_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
paint_tool_t \- A paint tool\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <paint_tools\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid_tool\fP"
.br
.ti -1c
.RI "char * \fBname_tool\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A paint tool\&. 


.PP
Definition at line 23 of file paint_tools\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int id_tool"

.PP
Definition at line 25 of file paint_tools\&.h\&.
.SS "char* name_tool"

.PP
Definition at line 26 of file paint_tools\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
