.TH "player_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player_t \- Reppresent a player\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <player\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBkey\fP [\fBNUMBER_KEY\fP]"
.br
.ti -1c
.RI "int \fBlife\fP"
.br
.ti -1c
.RI "int \fBbomb\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBinvincible\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reppresent a player\&. 


.PP
Definition at line 24 of file player\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int bomb"

.PP
Definition at line 28 of file player\&.h\&.
.SS "int id"

.PP
Definition at line 30 of file player\&.h\&.
.SS "int invincible"

.PP
Definition at line 31 of file player\&.h\&.
.SS "int key[\fBNUMBER_KEY\fP]"

.PP
Definition at line 26 of file player\&.h\&.
.SS "int level"

.PP
Definition at line 29 of file player\&.h\&.
.SS "int life"

.PP
Definition at line 27 of file player\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
