.TH "code/include/client-game/request_exchange.h" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/client-game/request_exchange.h \- File that descrive different request of exchange between a game client and game server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'level_display\&.h'\fP
.br
\fC#include 'player\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrequest_send_player_t\fP"
.br
.RI "The request that the server sends to the player\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtype_request_send_player_enum\fP { \fBREFRESH_LEVEL\fP = 1, \fBFREEZE_PLAYER\fP = 2, \fBEND_GAME\fP = 3 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
File that descrive different request of exchange between a game client and game server\&. 


.PP
\fBAuthor\fP
.RS 4
HADID Hocine & CHEMIN Pierre 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-03-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBrequest_exchange\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtype_request_send_player_enum\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIREFRESH_LEVEL \fP\fP
.TP
\fB\fIFREEZE_PLAYER \fP\fP
.TP
\fB\fIEND_GAME \fP\fP
.PP
Definition at line 17 of file request_exchange\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
