.TH "response_server_udp_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
response_server_udp_t \- Structure that contains the response of the server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network_request\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype_request\fP"
.br
.ti -1c
.RI "\fBcontent_response_server_t\fP \fBcontent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains the response of the server\&. 


.PP
Definition at line 77 of file network_request\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcontent_response_server_t\fP content"

.PP
Definition at line 80 of file network_request\&.h\&.
.SS "int type_request"

.PP
Definition at line 79 of file network_request\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
