.TH "SList_trap" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SList_trap \- A trap block, which is a list of trap boxess\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtrap_t\fP * \fBtraps\fP"
.br
.ti -1c
.RI "struct \fBSList_trap\fP * \fBsucc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A trap block, which is a list of trap boxess\&. 


.PP
Definition at line 31 of file trap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBSList_trap\fP* succ"

.PP
Definition at line 34 of file trap\&.h\&.
.SS "\fBtrap_t\fP* traps"

.PP
Definition at line 33 of file trap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
