.TH "sprite_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sprite_t \- The structure of a sprite\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sprite\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtype_sprite_enum\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBspecification\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure of a sprite\&. 


.PP
Definition at line 47 of file sprite\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int specification"

.PP
Definition at line 49 of file sprite\&.h\&.
.SS "\fBtype_sprite_enum\fP type"

.PP
Definition at line 48 of file sprite\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
