.TH "STrap" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STrap \- A square of a trap\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBposX\fP"
.br
.ti -1c
.RI "int \fBposY\fP"
.br
.ti -1c
.RI "struct \fBSTrap\fP * \fBsucc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A square of a trap\&. 


.PP
Definition at line 19 of file trap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int posX"

.PP
Definition at line 21 of file trap\&.h\&.
.SS "int posY"

.PP
Definition at line 22 of file trap\&.h\&.
.SS "struct \fBSTrap\fP* succ"

.PP
Definition at line 23 of file trap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
