.TH "window_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBposx\fP"
.br
.ti -1c
.RI "int \fBposy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "WINDOW * \fBbox\fP"
.br
.ti -1c
.RI "WINDOW * \fBinner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file window\&.h\&.
.SH "Field Documentation"
.PP 
.SS "WINDOW* box"

.PP
Definition at line 10 of file window\&.h\&.
.SS "int height"

.PP
Definition at line 9 of file window\&.h\&.
.SS "WINDOW* inner"

.PP
Definition at line 11 of file window\&.h\&.
.SS "int posx"

.PP
Definition at line 8 of file window\&.h\&.
.SS "int posy"

.PP
Definition at line 8 of file window\&.h\&.
.SS "int width"

.PP
Definition at line 9 of file window\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
