.TH "world_info_t" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
world_info_t \- Represents the information of a world\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <world_info\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdoors_level\fP [\fBNUMBER_DOOR\fP][2]"
.br
.ti -1c
.RI "int \fBtotal_level\fP"
.br
.ti -1c
.RI "\fBlevel_info_t\fP * \fBlevels\fP"
.br
.ti -1c
.RI "int \fBstart_level\fP"
.br
.ti -1c
.RI "int \fBexit_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the information of a world\&. 


.PP
Definition at line 25 of file world_info\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int doors_level[\fBNUMBER_DOOR\fP][2]"

.PP
Definition at line 27 of file world_info\&.h\&.
.SS "int exit_level"

.PP
Definition at line 33 of file world_info\&.h\&.
.SS "\fBlevel_info_t\fP* levels"

.PP
Definition at line 30 of file world_info\&.h\&.
.SS "int start_level"

.PP
Definition at line 32 of file world_info\&.h\&.
.SS "int total_level"

.PP
Definition at line 29 of file world_info\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
