.TH "code/include/game-control/world_info.h" 3 "Sun Apr 2 2023" "Version 1.0" "Starlyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/include/game-control/world_info.h \- File that manage world_info\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'level_info\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBworld_info_t\fP"
.br
.RI "Represents the information of a world\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUMBER_DOOR\fP   99"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBload_world_info\fP (\fBworld_info_t\fP *world_info, char *name_world)"
.br
.RI "Load a world\&. "
.ti -1c
.RI "void \fBdelete_world_info\fP (\fBworld_info_t\fP *world_info)"
.br
.RI "Delete a world from memory\&. "
.in -1c
.SH "Detailed Description"
.PP 
File that manage world_info\&. 


.PP
\fBAuthor\fP
.RS 4
HADID Hocine & CHEMIN Pierre 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-03-31
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBworld_info\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define NUMBER_DOOR   99"

.PP
Definition at line 19 of file world_info\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void delete_world_info (\fBworld_info_t\fP * world_info)"

.PP
Delete a world from memory\&. 
.PP
\fBParameters\fP
.RS 4
\fIworld_info\fP The world we want to suppress 
.RE
.PP

.PP
Definition at line 98 of file world_info\&.c\&.
.SS "void load_world_info (\fBworld_info_t\fP * world_info, char * name_world)"

.PP
Load a world\&. 
.PP
\fBParameters\fP
.RS 4
\fIworld_info\fP The variable that will contain the world's information 
.br
\fIname_world\fP The name of the world that we charge 
.RE
.PP

.PP
Definition at line 11 of file world_info\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Starlyze from the source code\&.
